version: 2
updates:
  # Backend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

  # Frontend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"