# SaaS Benchmarks Platform - Staging Environment Secrets
# This manifest defines sensitive configuration data and credentials
# Secrets are encrypted at rest and in transit using AES-256
# Auto-rotation enabled with 30-day interval

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: saas-benchmarks-staging
  labels:
    app: saas-benchmarks
    environment: staging
  annotations:
    kubernetes.io/service-account.name: saas-benchmarks-staging
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:role/saas-benchmarks-staging-secrets
    secrets.k8s.aws/rotation-interval: "30d"
    secrets.k8s.aws/auto-reload: "true"
type: Opaque
data:
  host: ${base64_encoded_value}
  port: ${base64_encoded_value}
  database: ${base64_encoded_value}
  username: ${base64_encoded_value}
  password: ${base64_encoded_value}

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: saas-benchmarks-staging
  labels:
    app: saas-benchmarks
    environment: staging
  annotations:
    kubernetes.io/service-account.name: saas-benchmarks-staging
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:role/saas-benchmarks-staging-secrets
    secrets.k8s.aws/rotation-interval: "30d"
    secrets.k8s.aws/auto-reload: "true"
type: Opaque
data:
  host: ${base64_encoded_value}
  port: ${base64_encoded_value}
  password: ${base64_encoded_value}

---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-credentials
  namespace: saas-benchmarks-staging
  labels:
    app: saas-benchmarks
    environment: staging
  annotations:
    kubernetes.io/service-account.name: saas-benchmarks-staging
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:role/saas-benchmarks-staging-secrets
    secrets.k8s.aws/rotation-interval: "30d"
    secrets.k8s.aws/auto-reload: "true"
type: Opaque
data:
  client_id: ${base64_encoded_value}
  client_secret: ${base64_encoded_value}
  redirect_uri: ${base64_encoded_value}

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: saas-benchmarks-staging
  labels:
    app: saas-benchmarks
    environment: staging
  annotations:
    kubernetes.io/service-account.name: saas-benchmarks-staging
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:role/saas-benchmarks-staging-secrets
    secrets.k8s.aws/rotation-interval: "30d"
    secrets.k8s.aws/auto-reload: "true"
type: Opaque
data:
  secret: ${base64_encoded_value}