# Tempo Configuration v2.2.x
# Production configuration for SaaS Benchmarks Platform distributed tracing

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: info
  max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 4MB
  grpc_server_max_send_msg_size: 4MB

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
          max_recv_msg_size: 4MB
          max_concurrent_streams: 1000
        thrift_http:
          endpoint: 0.0.0.0:14268
          max_request_body_size: 4MB
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          max_recv_msg_size: 4MB
          max_concurrent_streams: 1000
        http:
          endpoint: 0.0.0.0:4318
          max_request_body_size: 4MB
          cors_allowed_origins: ["*"]
  
  # High availability cluster configuration
  ha_cluster:
    enabled: true
    prefix: tempo/
    member_id: ${HOSTNAME}
    max_join_retries: 10
    join_retry_interval: 30s

ingester:
  trace_idle_period: 30s
  max_block_duration: 5m
  complete_block_timeout: 5m
  flush_check_period: 30s
  max_transfer_retries: 3
  
  # Lifecycler configuration for HA
  lifecycler:
    ring:
      replication_factor: 3
      kvstore:
        store: consul
        prefix: tempo/
        consul:
          host: consul:8500
          acl_token: ${CONSUL_ACL_TOKEN}

compactor:
  compaction:
    block_retention: 24h
    compacted_block_retention: 1h
    compaction_window: 1h
    max_block_bytes: 100MB
    max_compaction_objects: 1000000
    retries: 3
    chunk_size_bytes: 1MB
    flush_size_bytes: 1GB
    compaction_cycle: 30m

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: s3.amazonaws.com
      region: us-west-2
      access_key: ${AWS_ACCESS_KEY}
      secret_key: ${AWS_SECRET_KEY}
      insecure: false
      server_side_encryption: AES256
    
    pool:
      max_workers: 100
      queue_depth: 10000
      timeout: 30s
    
    wal:
      path: /var/tempo/wal
      encoding: snappy
    
    cache:
      enabled: true
      backend: redis
      redis:
        endpoint: redis:6379
        password: ${REDIS_PASSWORD}
        db: 0
        max_idle_conns: 10
        dial_timeout: 5s
        read_timeout: 3s
        write_timeout: 3s

# Global overrides for resource limits and features
overrides:
  max_bytes_per_trace: 50000
  max_search_bytes_per_trace: 10000
  max_bytes_per_tag_values_query: 5000
  ingestion_rate_limit_bytes: 15000000
  ingestion_burst_size_bytes: 20000000
  metrics_generator_processors:
    - service-graphs
    - span-metrics
  max_global_traces_per_user: 1000000
  max_search_duration: 30m