# Loki Configuration v2.8.x
# Purpose: Log aggregation system configuration for SaaS Benchmarks Platform
# Optimized for high performance, reliability and comprehensive monitoring

# Server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 4194304  # 4MB
  log_level: info
  http_server_idle_timeout: 120s
  grpc_server_max_concurrent_streams: 1000

# Ingester configuration for efficient log processing
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  flush_check_period: 30s
  max_chunk_size: 1048576  # 1MB
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 512MB

# Schema configuration for log storage
schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration for log persistence
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
    resync_interval: 5m
  filesystem:
    directory: /loki/chunks
    sync_period: 5m

# Query and ingestion limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_entries_limit_per_query: 5000
  max_query_series: 500
  max_query_lookback: 720h  # 30 days
  max_query_length: 721h
  max_concurrent_queries: 20
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB

# Chunk configuration for optimal storage
chunk_store_config:
  max_look_back_period: 720h  # 30 days
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 1073741824  # 1GB
      validity: 24h

# Table manager for efficient index management
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days
  poll_interval: 24h

# Compactor configuration for storage optimization
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Analytics configuration
analytics:
  reporting_enabled: false

# Query frontend configuration
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 100
  query_stats_enabled: true

# Query scheduler configuration
query_scheduler:
  max_outstanding_requests_per_tenant: 100
  scheduler_address: localhost:9095

# Ruler configuration for alerts
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  poll_interval: 1m
  concurrent_executions: 10

# Memberlist configuration for clustering
memberlist:
  join_members:
    - loki:7946
  dead_node_reclaim_time: 30s
  gossip_interval: 5s
  gossip_nodes: 3
  retransmit_factor: 2
  packet_dial_timeout: 5s
  packet_write_timeout: 5s